### PR TITLE
[ALPHA] alpha adjustments without bootstrap3

### PR DESCRIPTION
**Pull request by Zauberstuhl**
related to #120

### CODE REVIEW

**Comment by Flaburgan** [comment]
So how did you choose to go with that, one gem compatible with both 0.5.x and 0.6.x branches, or two gems?

**Comment by Zauberstuhl** [comment]
there are now following versions available:

`gem "rails-assets-diaspora_jsxc", "~> 0.1.4.develop.1", source: "https://rails-assets.org"`
`gem "rails-assets-diaspora_jsxc", "~> 0.1.4.alpha.1", source: "https://rails-assets.org"`

**Comment by Zauberstuhl** [comment]
@Flaburgan check https://github.com/diaspora/diaspora/pull/6334 and https://github.com/diaspora/diaspora/pull/6333

**Comment by Flaburgan** [comment]
Awesome <3

**Pull request merged**
